sprint 14
Vanchey359/java-shareit pull request #2
Opened 2023-05-05 21:08 UTC by Vanchey359

2023-05-06 20:57 UTC, kalitva requested changes

2023-05-06 20:57 UTC, kalitva commented on pom.xml
> +			<artifactId>postgresql</artifactId>
Постгрес уже объявлена выше

2023-05-06 20:57 UTC, kalitva commented on pom.xml
> +			<artifactId>hibernate-core</artifactId>
Нам не нужно явно hibernate добавлять, эта зависимость подтягивается вместе с `spring-boot-starter-data-jpa`

2023-05-06 20:57 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @Column(name = "start_date", nullable = false)
`nullable = false` это DDL декларация, нужна когда хибернейт генерирует схему. У нас схема мы сами пишем, так что можешь удалить все `nullable`

2023-05-06 20:57 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @Column(name = "status", length = 20)
Если имя поля совпадает с именем колонки в бд, `name` можно не указывать

2023-05-06 20:57 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/storage/BookingRepository.java
> +    List<Booking> findAllByBookerAndStartBeforeAndEndAfter(User booker, LocalDateTime start, LocalDateTime end, Sort sort);
Мы можем искать, передавая не объект а его айди? `findAllByBookerIdAnd...`

2023-05-06 20:57 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    private final String userHeaderId = "X-Sharer-User-Id";
Оформи поле как константу

2023-05-06 20:57 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/dto/CommentMapper.java
> +    public static Comment toCommentModel(CommentDto commentDto) {
Давай обойдемся без статических методов, сделай методы инстанс, поставь `@Component` и завайри маппер в сервис

2023-05-06 20:57 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +    public static ItemDto toItemDto(Item item) {
`toItemDto --> toDto`

2023-05-06 20:57 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +    public static Item toItemModel(ItemDto itemDto, User owner) {
`toItemModel --> toItem`

2023-05-06 20:57 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +    public static List<ItemDto> toItemDtoList(List<Item> items) {
`toItemDtoList --> toDtos`

2023-05-06 20:57 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +        for (Item item : items) {
Давай через стрим

2023-05-06 20:57 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    List<Item> findAllByOwnerId(Long ownerId);
`findAllByOwnerId --> findByOwnerId`

2023-05-06 20:57 UTC, kalitva commented on src/main/resources/schema.sql
> +DROP TABLE IF EXISTS users, items, comments, bookings;
Нет) Приложение, которое при запуске удаляет все данные из бд, это не то, что нам нужно. Ты же вроде к h2 подключаешься? Она в памяти хранит данные, так что при перезапуске приложения данные удалятся и так

И вообще желательно чтобы ты установил у себя postgres  и приложение подключалось к ней

2023-05-06 20:57 UTC, kalitva commented on src/main/java/ru/practicum/shareit/exception/ObjectNotFoundException.java
> +public class ObjectNotFoundException extends RuntimeException {
Кстати, можешь поставить аннотацию `ResponseStatus`, спринг обработает исключение и вернет статус, который ты передашь в аннотацию. Обработчик в `@RestControllerAdvice` можно удалить

`@ResponseStatus(HttpStatus.NOT_FOUND)`

2023-05-07 14:14 UTC, Vanchey359 commented on src/main/java/ru/practicum/shareit/exception/ObjectNotFoundException.java
> +public class ObjectNotFoundException extends RuntimeException {
Попробовал, очень странно но так валятся некоторые тесты (именно на эту ошибку)

2023-05-08 12:02 UTC, kalitva approved these changes

2023-05-08 12:02 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        List<Booking> bookingsList = new ArrayList<>();
Лучше `bookingsList --> bookings`

2023-05-08 12:02 UTC, kalitva commented on src/main/java/ru/practicum/shareit/exception/ObjectNotFoundException.java
> +public class ObjectNotFoundException extends RuntimeException {
Да, действительно странно. А ты удалил только метод, который обрабатывает `ObjectNotFoundException`  или весь контроллер?

2023-05-08 12:02 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/service/BookingState.java
> +package ru.practicum.shareit.booking.service;
Это нужно переместить в `model`

2023-05-08 12:02 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/service/BookingMapper.java
> +package ru.practicum.shareit.booking.service;
Маппер точно не должен находиться в пакете `service`, предлагаю положить в `dto`

2023-05-08 12:02 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
>  package ru.practicum.shareit.item.service.impl;
Думаю, `impl` здесь лишний, можно положить в пакет `service`

2023-05-08 16:01 UTC, Vanchey359 commented on src/main/java/ru/practicum/shareit/exception/ObjectNotFoundException.java
> +public class ObjectNotFoundException extends RuntimeException {
И только метод пробовал, и все ошибки переделывал по одной таким образом  и полностью контроллер удалял - валит тесты только по 1-2 ошибкам, сам не понимаю как так, вроде ничего не должно меняться

2023-05-08 18:13 UTC, merged