sprint 15 + add tests
Vanchey359/java-shareit pull request #3
Opened 2023-05-24 16:31 UTC by Vanchey359

2023-05-25 16:10 UTC, kalitva requested changes

2023-05-25 16:10 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/dto/BookingMapper.java
> +    public static BookingDto toDto(Booking booking) {
Почему сделал static? Поправь обратно

2023-05-25 16:10 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +}
Большинство этих методов можно убрать, используя `Specification` для фильтрации объектов, попробуй

https://spring.io/blog/2011/04/26/advanced-spring-data-jpa-specifications-and-querydsl

2023-05-25 16:10 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    List<BookingDto> getAllByOwner(Long userId, BookingState state, int from, int size);
Давай вместо `from` и `size` принимать `Pageable`, 4 параметра - многовато

2023-05-25 16:10 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/dto/CommentMapper.java
> +    public static Comment toComment(CommentDto commentDto) {
Из всех мапперов убери статик

2023-05-25 16:10 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>  import javax.persistence.*;
wildcard импорты лучше не использовать

https://google.github.io/styleguide/javaguide.html#s3.3.1-wildcard-imports

2023-05-25 16:10 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    List<Item> findAllByRequestId(Long requestId);
Лучше `findAllByRequestId --> findByRequestId`

Для всех таких случаев

2023-05-25 16:10 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    List<ItemDto> getAllByUserId(Long userId, int from, int size);
Тоже, давай принимать `Pageable`

2023-05-25 16:10 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        return itemsDto;
`itemsDto --> itemDtos`

2023-05-25 16:10 UTC, kalitva commented on src/test/java/ru/practicum/shareit/booking/BookingBriefDtoTest.java
> +    JacksonTester<BookingBriefDto> json;
private

2023-05-27 08:18 UTC, kalitva approved these changes

2023-05-27 08:18 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        checkSearchingParams(from, size);
Для проверки лучше конечно использовать `javax.validation` аннотации (чтобы заработало нужно поставить `@Validated` на уровне класса)

```java
@RequestParam(defaultValue = "0") @PositiveOrZero int from,
```

2023-05-27 08:18 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +        ItemDto mappedItem = new ItemDto();
`mappedItem --> dto`

2023-05-27 08:18 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +        Item mappedItem = new Item();
`mappedItem --> item`

2023-05-27 08:18 UTC, kalitva commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +    @NotBlank
Поля с аннотациями лучше отделять пустыми линиями чтобы было удобнее читать

2023-05-27 08:18 UTC, kalitva commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    private final String userHeaderId = "X-Sharer-User-Id";
https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names

2023-05-27 08:18 UTC, kalitva commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    @SneakyThrows
Не советую эту аннотацию испльзовать вообще. В случае тестов следует добавить `throws` в сигнатуру метода

2023-05-27 08:18 UTC, kalitva commented on src/test/java/ru/practicum/shareit/item/IntegrationItemTest.java
> +public class IntegrationItemTest {
Из названия непонятно какой класс тестируется

2023-05-27 12:31 UTC, Vanchey359 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    private final String userHeaderId = "X-Sharer-User-Id";
почему то чекстайл ругается когда я правильно указываю имя константы - сколько раз не запускал, все время разные подсвечивает. Приходится называть их не по правилам

2023-05-27 12:37 UTC, merged